[warm]
src.github = "ZL-Audio/ZLWarm"
fetch.github = "ZL-Audio/ZLWarm"
git.fetchSubmodules = true

[lmakeup]
src.github = "ZL-Audio/ZLLMakeup"
fetch.github = "ZL-Audio/ZLLMakeup"
git.fetchSubmodules = true

[lmatch]
src.github = "ZL-Audio/ZLLMatch"
fetch.github = "ZL-Audio/ZLLMatch"
git.fetchSubmodules = true

[inflator]
src.github = "ZL-Audio/ZLInflator"
fetch.github = "ZL-Audio/ZLInflator"
git.fetchSubmodules = true
