[punkott]
src.git = "https://github.com/gmoican/PunkOTT.git"
fetch.git = "https://github.com/gmoican/PunkOTT.git"
git.fetchSubmodules = true

[catch2]
src.manual = "v3.8.1"
fetch.github = "catchorg/Catch2"
