name: Update sources
on:
  workflow_dispatch:
  schedule:
    - cron: 15 5 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: staging

      - name: Setup Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            keep-env-derivations = true
            keep-outputs = true
            accept-flake-config = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: bandithedoge
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update sources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix flake update --commit-lock-file
          echo -e '[keys]\ngithub = "${{ secrets.GITHUB_TOKEN }}"' > keyfile.toml
          chmod +x fetch.nu
          nix develop .#update -c ./fetch.nu --commit
          rm keyfile.toml
          git add -A

      - name: Generate package list
        run: nix eval --raw .#_LIST > LIST.md

      - name: Format code
        run: nix fmt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update sources"
          git push
