name: Update sources
on:
  workflow_dispatch:
  schedule:
    - cron: 15 5 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ci-hoover
        uses: xd009642/ci-hoover@0.1.1

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: staging

      - name: Setup Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            keep-env-derivations = true
            keep-outputs = true
            accept-flake-config = true

      - name: Restore cache
        id: cache-restore
        uses: nix-community/cache-nix-action/restore@v6
        with:
          primary-key: update-${{ runner.os }}

      - name: Update sources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nix flake update --commit-lock-file
          echo -e '[keys]\ngithub = "${{ secrets.GITHUB_TOKEN }}"' > keyfile.toml
          chmod +x fetch.nu
          nix develop .#update -c ./fetch.nu --commit
          rm keyfile.toml
          git add -A

      - name: Generate package list
        run: nix eval --raw .#_LIST > LIST.md

      - name: Format code
        run: nix fmt

      - name: Save cache
        uses: nix-community/cache-nix-action/save@v6
        if: always() && steps.cache-restore.outputs.hit-primary-key != 'true'
        with:
          primary-key: update-${{ runner.os }}
          gc-max-store-size: 1G
          purge: true

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update sources"
          git push
